// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHnuip0Pkl--bbDn2vZSWps8rp_WUAKPI',
    appId: '1:690802531741:web:8d7bc0d6dfba01e871e374',
    messagingSenderId: '690802531741',
    projectId: 'smart-attendance-2026-v2',
    authDomain: 'smart-attendance-2026-v2.firebaseapp.com',
    storageBucket: 'smart-attendance-2026-v2.firebasestorage.app',
    measurementId: 'G-GHBNM7VYDY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHSYFS-yfj1BJRJ77nIJHvaa_3jjCewGE',
    appId: '1:690802531741:android:58fd06f871cb231e71e374',
    messagingSenderId: '690802531741',
    projectId: 'smart-attendance-2026-v2',
    storageBucket: 'smart-attendance-2026-v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQUkzoaA840wTUA42w92og51FX6Hx8NIw',
    appId: '1:690802531741:ios:885de0aa725dd77f71e374',
    messagingSenderId: '690802531741',
    projectId: 'smart-attendance-2026-v2',
    storageBucket: 'smart-attendance-2026-v2.firebasestorage.app',
    iosBundleId: 'com.example.smartAttendanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQUkzoaA840wTUA42w92og51FX6Hx8NIw',
    appId: '1:690802531741:ios:885de0aa725dd77f71e374',
    messagingSenderId: '690802531741',
    projectId: 'smart-attendance-2026-v2',
    storageBucket: 'smart-attendance-2026-v2.firebasestorage.app',
    iosBundleId: 'com.example.smartAttendanceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHnuip0Pkl--bbDn2vZSWps8rp_WUAKPI',
    appId: '1:690802531741:web:b84c14d5a8b7e0af71e374',
    messagingSenderId: '690802531741',
    projectId: 'smart-attendance-2026-v2',
    authDomain: 'smart-attendance-2026-v2.firebaseapp.com',
    storageBucket: 'smart-attendance-2026-v2.firebasestorage.app',
    measurementId: 'G-YLX8CBE1SM',
  );

}